USER_24_PUBLIC__22dbt_practice1_22:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: SNOWFLAKE_LEARNING_DB
      schema: PUBLIC
